---
- name: "Scan for Updates"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "list update packages"
      shell: |
        zypper lu | sed -ne '/Reading installed packages.../,$ p' | sed '1,3d' | awk -F '|' '{ print $3, $4, $5, $6 }'
      register: list_package
    
    - name: "debug"
      debug:
        msg: "{{list_package}}"

    - name: "list update packages"
      shell: |
        zypper lp --with-optional | sed -ne '/Reading installed packages.../,$ p' | sed '/^$/d' | sed '1,4d' | sed -e '/The following updates are also available:/,+2d' | sed -e '/^Found/,$d' | awk -F '|' '{ print $2, $3, $4, $8}'
      register: list_patch

    - name: "debug"
      debug:
        msg: "{{list_patch}}"
